# Generated by Django 5.0.6 on 2024-05-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficdata',
            name='dest_ip',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='source_ip',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
